### ISSUE TITLE
Request: accept mutex boolean arguments to be provided if they are complementary

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#26]
For instance, in a command line tool with the following arguments:

```java
...
@Argument(fullName="arg1", mutex = {"arg2"}, optional = true)
public Boolean arg1 = false;
@Argument(fullName="arg2", mutex = {"arg1"}, optional = true)
public Boolean arg2 = false;
...
```

Will be useful to be able to provide the following to the command line and don't blow up:
* `--arg1 false --arg2 false`
* `--arg1 true --arg2 false`
* `--arg1 false --arg2 true`

And only throw an exception if `--arg1 true --arg2 true`.

**Comment by lbergelson** [comment]
@magicDGS I'm not sure that's the best behavior for mutex in this case.  I would argue that the behavior your describing would make sense for primitive `boolean`, but since you're using `Boolean` there is the possibility to have a `null` in those values.  To me, mutex means not to be specified together, and with nullable things I think we should respect the difference between null and anything else.

**Comment by magicDGS** [comment]
I used `Boolean` instead of the primitive as an example, but I get your point. The problem is if this mutex arguments change their defaults and the user wants to maintain a pipeline with all the parameters, the tool will not realize and the tool may fail.

Anyway, I thought more about it and it is difficult to say when they should thrown and when not, because they are treat as flags but also as param/value in the CMD.
