### ISSUE TITLE
Add support for argument tagging to barclay

### ISSUE THREAD

**Issue by droazen** [broadinstitute/barclay#29]
Currently in GATK4 we have some support for tagging arguments, but the tagging is done on the value side, and manually by the engine. Eg.,

```
-V myTag:my.vcf
```

This causes many issues: parsing ambiguity with URIs, interfering with shell auto-expansion, etc.

Let's add native tagging support to barclay, so that the tag can be on the argument side rather than the value side. Eg.,

```
-I:tumor my.bam
```

We also need to support arbitrary key/value pairs after the tag. Eg., 

```
-I:tumor,key=value,key2=value2
```

I think that the way to do this is to introduce a new `TaggedArgument` interface in barclay with methods to get/set both the tag and the optional key/value pairs. Eg.,

```
void setTag(String)
String getTag()
void setTagAttributes(Map<String, String> attributes)
Map<String, String> getTagAttributes()
```

The upcoming `URI` class in GATK will implement this interface. When barclay encounters an `@Argument`-annotated field of a type that implements the `TaggedArgument` interface, it should parse the tags and inject them into the object instance for that field via the setter methods.

**Comment by droazen** [comment]
For @cmnbroad

**Comment by cmnbroad** [comment]
Should we bake in a way to support @LeeTL1220's time series example ? I'm not sure how many there will be in a series; if its a only a few, the tool might be able to use predefined names. Otherwise we may want some order-preserving mechanism.

**Comment by cmnbroad** [comment]
Also, we might want to consider adding a way to declare the allowed tags and/or attributes, maybe in Argument or a separate annotation, so instead of the CLP displaying:

     -I,-I:FeatureInput

it could display something like:

      -I,-I: File
      Allowed tags: tumor, normal
      Allowed attributes truth, training

**Comment by droazen** [comment]
These are good ideas for future enhancements, but let's get the basic version described above in first -- we'll need it for hookup to GATK by early next week.

**Comment by cmnbroad** [comment]
@droazen Some questions on how this should work (from the CLP's perspective), and how to handle command line validation:

- Are attributes are always optional ?
- Is tag name always required for an option that implements `TaggedArgument` (I'm not sure FeatureInput [handles this](https://github.com/broadinstitute/gatk/issues/2144) correctly) ?
- Should tags be allowed for non-collections ?
- Should the CLP require tag names to be unique within a collection, or should we leave that up to the tool ?

**Comment by lbergelson** [comment]
@cmnbroad What's the time series use case?  

*  I don't think name should be required unless that's necessary from a parsing perspective (although I don't think it should be given that we can restrict characters in names arbitrarily).  
*  They're probably not always optional from a tool's perspective, but since they're such a niche feature anyway I think it's probably fine to just let it be the tools problem to check for them rather than add a complex api to specify required attributes.
*  I don't see any reason tags should be disallowed for non collections although you're probably doing something wrong if you're designing your tool that way.
* Leave uniqueness up to the tool.

**Comment by cmnbroad** [comment]
@lbergelson I think the time series use case is writing a tool that takes a series of inputs ordered by time (i.e., sequence reads from the same tumor tissue every N days). I'm not sure what the tagging requirements would be for that though, like how may inputs would be typical; if order would be established via command line order; or predefined tags; or tags that are timestamps, etc.

Requiring a tag name isn't necessary for parsing, but I have to do some rather ugly hashing/transformation of the arg list in a pre-parsing pass in order to get this to work, since I have to strip off the tag strings and store them to be retrieved later; otherwise the parser doesn't recognize the option name. I have a HashMap-based scheme that works, but it would be nice if there was a simpler way. Either way there are quite a few test permutations...
