### ISSUE TITLE
Parse javadoc link tag for improving user-readability in doclet

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/barclay#84]
Currently, if any tag is present linking to a different class in the javadoc, this is output as it is. This have two disadvantages: 1) developer javadoc could not include links if they are part of the documented features; 2) the help page does not have access to the linked class URL if that one is documented.

I have some suggestions to solve this problem:

* Populate this classes into the extraDoc. The user could use a macro in FreeMarker to substitute the `{@link ClassName}` pattern by the extraDoc URL or just remove the tag if not present.
* Parse the javadoc internally to add the URL as an HTML or Markdown formatted String. This is not the optimal solution, because it adds complexity to Barclay and it is less flexible.

I prefer the first option, and providing a file with macros for parsing this kind of information to be included by the user.

**Comment by vdauwera** [comment]
I favor the first option as well

**Comment by cmnbroad** [comment]
I'm not sure I quite understand the proposal (though I'm also not sure I see how this issue is much different from #83, or why it requires a different/more complicated solution). There seem to be a lot of different ways to embed links in javadoc, and I'm not really sure which ones we're talking about. I thought "link" tags were strictly for javadoc, whereas "see" is more general and links to javadoc or external ? Hopefully we can come up with a simple model to address them all - I'd definitely prefer a solution that doesn't require Freemarker-level post-processing.

**Comment by magicDGS** [comment]
Closing in favor of #85, where I tried to summarize the problems and my suggestions in a better way.
