### ISSUE TITLE
Provide annotation for tools to be "@Hidden"

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/barclay#92]
Like the annotation for arguments. 

Use case below has GATK developers in mind:
This enables developers (or groups of developers) to have/share tools that are for internal/prototyping only.
The reason that keeping a separate branch for such purpose does not work quite well is that one needs to constantly rebase the branch on master, which could be painful.

**Comment by magicDGS** [comment]
I think that this can be accomplished by using the `@BetaFeature` annotation without the `@DocumentedFeature` annotation: this will remove from the help documentation the tools and they will appear as beta in the command line. The summary/description should provide information about why the tools is beta, such as internal/prototyping only.

Do you agree with me on this, @cmnbroad? If not, I can change the code to handle `@Hidden` also for command line tools. In that case, we can enforce hidden tools to have the `@BetaFeature` annotation, because I do not think that tools should be hidden unless they are beta for whatever reason...

**Comment by cmnbroad** [comment]
Yes, I think the combination of:

- CommandLineProgramProperties.omitFromCommandLine=true
- `@BetaFeature` (without `@DocumentedFeature`)

should do it. And I'll close [this issue](https://github.com/broadinstitute/barclay/issues/18), since it sounds like we want to keep that feature.

@SHuang-Broad feel free to reopen this if for any reason its not adequate.

**Comment by SHuang-Broad** [comment]
Thanks @magicDGS and @cmnbroad , I just tried and it is working!

**Comment by SHuang-Broad** [comment]
Sorry for generating the false hope... The tool would be not listed if `./gatk-launch --list`, but this would also prevent the tool from being able to run. 

```
Exception in thread "main" org.broadinstitute.hellbender.exceptions.UserException: 
<TOOL> is not a valid command
```

**Comment by magicDGS** [comment]
In the current state of barclay, `CommandLineArgumentParser` is designed to populate the annotations to create the argument definitions and set the fields on the caller class with a String array (and generate documentation for this, but that's a different usage). Thus, there is no way to "hide" a tool from a toolkit such GATK.

Actually the `CommandLineProgramProperties.omitFromCommandLine` is not used on the command line parsing code, but on the the GATK's `Main` class. I think that barclay should remove the `omitFromCommandLine` field because it is confusing, and downstream toolkits as Picard/GATK should add a mechanism to allow hidden tools (from the CLI and documentation). Another option for this, that makes kind of sense, it's to add a field to the `BetaFeature` to ignore in the barclay documentation code; that field could be used afterwards by a `Main` class to remove also from the command line help. What do you think, @cmnbroad?

Anyway, for @SHuang-Broad, the solution for your issue is patching GATK here: https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/Main.java#L261

**Comment by cmnbroad** [comment]
@magicDGS I was actually thinking that we could just keep omitFromCommandLine in Barclay, and document/redefine it as being for use by the toolkit to honor (its unused except the line you mention above in GATK). And then we could patch GATK to honor it for the use @SHuang-Broad has in mind).

**Comment by magicDGS** [comment]
I was thinking also something different than that: maybe it is worthy to create the CLI structure in barclay to be a ready-to-go dependency to start implementing a toolkit. This requires:

* Simple `AbstractCommandLineProgram` class (without arguments) based on the GATK one, to be extended by tool developers. Then, GATK/Picard CLP could extend and add custom behaviour.
* A `MainTemplate` based on the GATK one to be extended by `Main` classes to be the entry point for the CLI. In this class is where where this issue will be addressed.

Like that, barclay will be an easy-to-use library to develop toolkits with associated documentation (and even bash-completion if a master script is implemented). I think that in the long term this is better than have downstream-handled features, and will also allow to integrate in a better way different toolkits (by sharing the `AbstractCommandLineProgram`).

For the @SHuang-Broad issue, the current code should be changed in GATK and it does not require any change in barclay; for a more robust library, I think that we can discuss this in other issue and/or PR implementing my idea.

@cmnbroad: let me know if you want me to submit a PR with the `AbstractCommandLineProgram` and `MainTemplate`

@SHuang-Broad: I think that this issue can be closed, because the fix should be done in GATK and not in barclay.

**Comment by cmnbroad** [comment]
@magicDGS I'm not sure how much incremental value it would add for toolkits to have these classes in Barclay. Perhaps I'm being myopic, but it seems like they would only impose structure, and not add much in the way of useful services. I think many of the outstanding PRs and issues we already have (most of which I'm the bottleneck on) would be higher priority.

**Comment by SHuang-Broad** [comment]
Thank you guys for taking on this so quickly! @magicDGS ' PR in GATK is working for me. 
Please feel free to close this when you think it's appropriate.

**Comment by magicDGS** [comment]
@cmnbroad, I don't think that it impose structure, but it provides an scheme to develop a toolkit. It does not require to be used, everyone can use their own `Main` and `CommandLineProgram` implementation as currently done in GATK/Picard and my downstream projects. But I think that it will add the following:

* Toolkit projects depending in barclay alone, can just extend `MainTemplate` with the main method and develop tools using `AbstractCommandLineProgram` and `runTool` (for example). Currently, toolkits should implement a `Main` class which looks for a `CommandLineProgram` class that is project-dependent; this can still be done with this proposal, but there is repeated code in GATK/Picard (and I guess that barclay-based toolkits will have it too) that can be removed by including it in barclay.
* Related to the the GATK/Picard related code, this will also help to "merge" toolkits: in the current state, the CLP is a completele unrelated class in GATK and Picard. Using an `AbstracCommandLineProgram` may simplify the search for tools implemented in other projects without changing the code. This will be useful for GATK, but also for downstream projects that wants to include both GATK/Picard utilities.

Maybe the CLP could be an interface to do not impose structure except a single method for running the tool; in the case of `MainTemplate`, that's more difficult, but maybe utilities for extracting the CLP and populate the arguments may be useful in barclay for sharing between downstream projects. Maybe `MainUtils` is a better name?

**Comment by magicDGS** [comment]
An I forgor: of course, the outstanding PR's are higher priority (I'm still waiting for a more consistent plugin contract).

**Comment by cmnbroad** [comment]
Closing via https://github.com/broadinstitute/gatk/pull/3486. Thanks @magicDGS! @SHuang-Broad give it a try!
